select * from customer_behavior;

--Q01. What is the total revenue generated by male vs female customers?

select gender, sum(purchase_amount) revenue
from customer_behavior
group by gender

--Female = 75191 vs male = 157890

--Q02. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_behavior)

--A sample of ten
--02	64
--03	73
--04	90
--07	85
--09	97
--12	68
--13	72
--16	81
--20	90
--22	62

--Q03. Which are the top 5 products with the highest average review rating?

select item_purchased, ROUND(AVG(rating)::numeric,2) avg_rating
from customer_behavior
group by item_purchased
order by AVG(rating) desc
limit 5;

--Gloves	3.86
--Sandals	3.84
--Boots		3.82
--Hat		3.80
--Skirt		3.79

--Q04. Compare the average Purchase Amounts between Standart and Express Shipping

select shipping_type, 
ROUND(AVG(purchase_amount)::numeric,2)
from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type

--Standard	58.46
--Express	60.48

--Q05. Do subscribed customers spend more? Compare average spend and total revenue between 
--subscribers and non-subscribers

select subscription_status,
COUNT(customer_id) total_customers,
ROUND(AVG(purchase_amount),0) avg_spend,
ROUND(SUM(purchase_amount),0) total_revenue
from customer_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

--Yes	1053	59	62645
--No	2847	60	170436

--Q06. Which 5 products have the highest percentage of purchse with discounts applied?
select item_purchased,
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) /COUNT(*),2) discount_rate
FROM customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;

--Hat		50.00
--Sneakers	49.66
--Coat		49.07
--Sweater	48.17
--Pants		47.37

--Q07. Segment customers into New, Returning, and loyal based on their total
--number of previous purchases, and show the count of each segment

with customer_type as (
select customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END customer_segment
from customer_behavior
)

select customer_segment, count(*) "Number of customers"
from customer_type
group by customer_segment
order by "Number of customers" desc

--Loyal		3116
--Returning	701
--New		83

--Q08. What are the top 3 most purchased product within each category?

with item_counts as (
select category, item_purchased,
COUNT(customer_id) total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc) item_rank
from customer_behavior
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

--01	"Accessories"	"Jewelry"		171
--02	"Accessories"	"Sunglasses"	161
--03	"Accessories"	"Belt"			161
--01	"Clothing"		"Blouse"		171
--02	"Clothing"		"Pants"			171
--03	"Clothing"		"Shirt"			169
--01	"Footwear"		"Sandals"		160
--02	"Footwear"		"Shoes"			150
--03	"Footwear"		"Sneakers"		145
--01	"Outerwear"		"Jacket"		163
--02	"Outerwear"		"Coat"			161

--Q09. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) repeat_buyers
from customer_behavior
where previous_purchases > 5 
group by subscription_status

--No	2518
--Yes	958

--Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc;

--Young Adult	62143
--Middle-aged	59197
--Adult			55978
--Senior		55763
